### ISSUE TITLE
time data None error

### ISSUE THREAD

**Issue by JamesOwers** [rbavishi/Habitican-Curse#5]
## Problem

Installed without sudo, ran `habitican-curse :help` and entered uuid and api copy and pasted from site. Was returned an error. I think this must have contained a space character at the end as it was copy pasted from the site so I assumed the uuid/api was incorrect. Deleted `~/.habiticarc` and reentered password on prompt (it would be good to be informed I was storing my password in plaintext). Reinstalled with sudo.  `habitican-curse :help`. Got the same error.
## System

OSX 10.10.5
## Stacktrace error

``` bash
Traceback (most recent call last):
  File "/Users/kungfujam/anaconda/bin/habitican-curse", line 45, in <module>
    curses.wrapper(main)
  File "/Users/kungfujam/anaconda/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/kungfujam/anaconda/bin/habitican-curse", line 30, in main
    G.reqManager.FetchData()
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse/request_manager.py", line 120, in FetchData
    item = T.TODO(i)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse/task.py", line 299, in __init__
    self.dueDate = H.DateTime(str(data['date'])).DueDateFormat()
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse/helper.py", line 176, in __init__
    self.date = self.ConvertDate(inpDate)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse/helper.py", line 193, in ConvertDate
    retDate = datetime.strptime(date,"%Y-%m-%dT%H:%M:%S.%fZ")
  File "/Users/kungfujam/anaconda/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'None' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

**Comment by rbavishi** [comment]
I apologize for the inconvenience. If I understand you correctly, the program crashes when you input the ":help" command? So it initializes properly and displays all the tasks? Are you using the latest version 2.1? If yes, can you confirm for me that the "Last update" data on the bottom is displayed correctly? Thanks a lot!

**Comment by JamesOwers** [comment]
I can't run at all, the same error is reproduced by typing `habitican-curse` and running, though I believe I'm on the latest:

``` bash
$ pip install habitican_curse
Collecting habitican-curse
Installing collected packages: habitican-curse
Successfully installed habitican-curse-2.1
```

Is there a reason I need to sudo? (error is reproduced with and without sudo)

**Comment by rbavishi** [comment]
No, I don't believe sudo/no sudo makes a difference here. I think the problem lies with the JSON response returned by Habitica. I may have forgotten to add more exception handling. I've added a patch file named `task.txt`. For your convenience I've added the commands you have to execute -

```
cd /Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse/

patch task.py < task.txt (Github doesn't support .patch files)
```

If you have cloned the repository, I've committed the changes, so you can pull them up to see if it works now.

Alternatively, the quickest method would be that you manually edit the `task.py` file in the above directory. Change line 298 from -

```
data.has_key('date') and data['date'] != "": #Due Date Stuff
```

to 

```
data.has_key('date') and data['date'] != "" and data['date'] != None: # Due Date Stuff
```

Please let me know if this works. Thanks a lot!
[task.txt](https://github.com/rbavishi/Habitican-Curse/files/37556/task.txt)

**Comment by rbavishi** [comment]
Also I've handled the trailing white-space error you had while inputting the UUID and API-KEY. I've attached the patch file in case you haven't cloned the repository. If the errors are resolved, I'll push the final changes to the PyPI server
[request_manager.txt](https://github.com/rbavishi/Habitican-Curse/files/38234/request_manager.txt)

**Comment by JamesOwers** [comment]
This didn't work this evening (same error after applying patch and reinstalling with `pip`). Will try again tomorrow.

**Comment by rbavishi** [comment]
I managed to reproduce your error, sometimes the date field for a task in the JSON response by Habitica is None, or sometimes not even present. Had to introduce exception handling. I've identified all holes that could possibly lead to this. I have released a new version 2.1.1 incorporating those changes. You can enter `sudo pip install --upgrade habitican_curse` to check the new version

Please let me know if this works. Thanks again!

**Comment by rbavishi** [comment]
On a side note, about your comment on the storage of passwords - There really is no other way. I don't want to waste user time by making them enter a password which can decrypt the txt file everytime you launch the program. I can't enter a secret password in the program itself as the code is open source. The only way to solve this would be to protect your txt files from being read by an external computer through file access permissions.

**Comment by JamesOwers** [comment]
storing password fine, maybe just add a note making that explicit (i had to
dig in the source to find the dotfile I didn't know had been created)

**Comment by JamesOwers** [comment]
Good and bad news. Bad news, error is still there:

``` bash
pip install --upgrade habitican_curse
Collecting habitican-curse
  Downloading habitican_curse-2.1.1.tar.gz
Building wheels for collected packages: habitican-curse
  Running setup.py bdist_wheel for habitican-curse
  Stored in directory: /Users/kungfujam/Library/Caches/pip/wheels/ad/3e/c4/d68cef26e8ba0f7d17001c4c6414dcf07bdee62a9445db3cf1
Successfully built habitican-curse
Installing collected packages: habitican-curse
  Found existing installation: habitican-curse 2.1
    Uninstalling habitican-curse-2.1:
      Successfully uninstalled habitican-curse-2.1
Successfully installed habitican-curse-2.1.1
c105043:Habitican-Curse kungfujam$ habitican-curse
Traceback (most recent call last):
  File "/Users/kungfujam/anaconda/bin/habitican-curse", line 45, in <module>
    curses.wrapper(main)
  File "/Users/kungfujam/anaconda/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/kungfujam/anaconda/bin/habitican-curse", line 30, in main
    G.reqManager.FetchData()
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse/request_manager.py", line 120, in FetchData
    item = T.TODO(i)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse/task.py", line 299, in __init__
    self.dueDate = H.DateTime(str(data['date'])).DueDateFormat()
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse/helper.py", line 176, in __init__
    self.date = self.ConvertDate(inpDate)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse/helper.py", line 193, in ConvertDate
    retDate = datetime.strptime(date,"%Y-%m-%dT%H:%M:%S.%fZ")
  File "/Users/kungfujam/anaconda/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2015-12-28T21:52:13Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

Good news, I know why. The strings are not consistent: sometimes they have a millisecond component, sometimes not. You can just use a trycatch to sweep them up. 

More bad news, new error after doing that!

``` bash
$ habitican-curse
Traceback (most recent call last):
  File "/Users/kungfujam/anaconda/bin/habitican-curse", line 45, in <module>
    curses.wrapper(main)
  File "/Users/kungfujam/anaconda/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/kungfujam/anaconda/bin/habitican-curse", line 30, in main
    G.reqManager.FetchData()
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse/request_manager.py", line 120, in FetchData
    item = T.TODO(i)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse/task.py", line 306, in __init__
    self.checklistMenu = ChecklistMenu(self.checklist)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse/task.py", line 62, in ChecklistMenu
    task_item = ChecklistItem(i)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse/task.py", line 146, in __init__
    self.text      = str(data['text'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 18: ordinal not in range(128)
```

To reproduce, replace relevant lines in `helper.py` to:

``` python
    def ConvertDate(self, date):
    if type(date) == datetime:
        retDate = date.replace(tzinfo=tz.tzlocal())
        return retDate

        elif type(date) == int or type(date) == float:
            # Milliseconds included in the timestamp
            retDate = datetime.fromtimestamp(date*1.0/1000) 
        retDate = retDate.replace(tzinfo=tz.tzlocal())

        return retDate

        elif type(date) == str:
            # UTC Format. We'll convert it to local time.
            # We assume that local time zone can be computed by dateutil
            try:
                retDate = datetime.strptime(date,"%Y-%m-%dT%H:%M:%S.%fZ")
            except ValueError:
                retDate = datetime.strptime(date,"%Y-%m-%dT%H:%M:%SZ")


            retDate = retDate.replace(tzinfo=tz.tzutc()) # UTC Time zone convert
            retDate = retDate.astimezone(tz.tzlocal())   # Local Time

            return retDate

    def ConvertUTC(self):
        retDate = self.date.replace(tzinfo=tz.tzlocal())
        retDate = retDate.astimezone(tz.tzutc())
        try:
            res = retDate.strftime("%Y-%m-%dT%H:%M:%S.%fZ")
        except ValueError:
            res = retDate.strftime("%Y-%m-%dT%H:%M:%SZ")
    return res
```

**Comment by rbavishi** [comment]
Aah, the date-time error was a good catch. Your fix works perfectly. The second error, however, is completely unrelated. Just exposes a series of rookie mistakes I made. I completely forgot to take French into account :) . '\xe9' stands for é, represented in unicode. I was committing the grave mistake of converting it straight to 'str'. I managed to reproduce your error completely, and have introduced fixes. Have attached a file 'format_patch.txt'. Please let me know if this works (I really hope it does now). Thanks a lot for your patience. I've added the commands just for your convenience.

```
cd /Users/kungfujam/anaconda/lib/python2.7/site-packages/habitican_curse
sudo patch < <path-to-file>/format_patch.txt
```

[format_patch.txt](https://github.com/rbavishi/Habitican-Curse/files/39772/format_patch.txt)

**Comment by JamesOwers** [comment]
SUCCESS!!! Pleasure to help out. Nice job fixing.

<img width="1057" alt="screen shot 2015-11-20 at 14 10 56" src="https://cloud.githubusercontent.com/assets/3524723/11301636/98457564-8f90-11e5-9a2a-de06891c2a6a.png">

As an aside, me and a few mates are making a command line tool for summarising battles. Feel free to check it out and steal some code for your `:party` function. https://github.com/kungfujam/habitica_hacks.

**Comment by rbavishi** [comment]
Awesome! Thanks a lot! Will definitely check out your project.
